export const WHATSAPP = import.meta.env.VITE_WHATSAPP_NO || '919876543210'

export const PHOTOGRAPHER = {
  name: 'Ayush Divani',
  place: 'Gujarat, India & Worldwide',
  shootsCompleted: 160,
  awardsCount: 11,
}

export const photos = [
  {
    id: 'root-1748261787226',
    title: 'Aura in Ochre',
    category: 'Portraits',
    w: 3072,
    h: 4096,
    year: '2024',
    awards: 'Staff Pick',
    location: 'Old Ahmedabad Pols',
    story: 'Captured at 7:15 AM as morning sunlight filtered through 200-year-old carved wooden jharokhas.',
    exif: {
      camera: 'Sony A7R V',
      lens: '85mm f/1.4 GM',
      settings: '1/640s · f/1.8 · ISO 100',
      focalLength: '85mm',
      aperture: 'f/1.8',
    },
    lqip: 'data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAAAQBQCdASoUABsAPu1qqVAppiOiqA1RMB2JagAu/8D5IBfvPm6rCkUG9UqtJCsPeikAAP76WrRExq6r0PyvyzYR8Yoc6XG5NXS3jf6JC6jiSbkzDcl1flUx1xz3po5POQMMCLphIMocNi6R4UeBHhR4XZn3sk/JC5bDXzNhPU/ViJ1lMYjy9HK+hF26RQQwTMij+PNaA2TqRLdOaLNQ2AAA',
  },
  {
    id: 'unsplash-portrait-01',
    title: 'Devotion in Natural Light',
    category: 'Portraits',
    w: 600,
    h: 800,
    year: '2025',
    awards: 'Vogue Spotlight',
    location: 'Heritage Courtyard, Patan',
    story: 'Gentle bounce light highlighting natural expressions without synthetic reflectors.',
    exif: {
      camera: 'Sony A7 IV',
      lens: '85mm f/1.4 GM',
      settings: '1/500s · f/1.4 · ISO 100',
      focalLength: '85mm',
      aperture: 'f/1.4',
    },
    remote: 'https://images.unsplash.com/photo-1790773941260-d7a24d124c7f?w=1200&auto=format&fit=crop&q=80',
  },
  {
    id: 'root-img-20220824-185013',
    title: 'Saffron Monolith',
    category: 'Architecture & Street',
    w: 3000,
    h: 4000,
    year: '2024',
    awards: 'Better Photo Finalist',
    location: 'Adalaj Stepwell',
    story: 'Geometric subterranean corridors sculpted by fifth-century sandstone architecture.',
    exif: {
      camera: 'Fujifilm GFX 100S',
      lens: '45mm f/2.8 WR',
      settings: '1/250s · f/4.0 · ISO 160',
      focalLength: '45mm',
      aperture: 'f/4.0',
    },
  },
  {
    id: 'unsplash-portrait-02',
    title: 'Ephemeral Silhouette',
    category: 'Editorial',
    w: 600,
    h: 800,
    year: '2025',
    awards: "Editor's Choice",
    location: 'Atelier Minimal, Ahmedabad',
    story: 'High contrast interplay between negative space and graceful silhouette contour.',
    exif: {
      camera: 'Sony A7R V',
      lens: '35mm f/1.4 GM',
      settings: '1/800s · f/2.0 · ISO 125',
      focalLength: '35mm',
      aperture: 'f/2.0',
    },
    remote: 'https://images.unsplash.com/photo-1790773882461-2ae7b3334c67?w=1200&auto=format&fit=crop&q=80',
  },
  {
    id: 'root-img-20250823-120721',
    title: 'Echoes of Stone',
    category: 'Architecture & Street',
    w: 6144,
    h: 8192,
    year: '2025',
    awards: 'Featured Archive',
    location: 'Rani ki Vav, Patan',
    story: 'UNESCO World Heritage stepwell carvings preserved in midday directional shadows.',
    exif: {
      camera: 'Fujifilm GFX 100S',
      lens: '30mm f/3.5 WR',
      settings: '1/160s · f/8.0 · ISO 200',
      focalLength: '30mm',
      aperture: 'f/8.0',
    },
  },
  {
    id: 'unsplash-portrait-04',
    title: 'The Saffron Veil',
    category: 'Editorial',
    w: 600,
    h: 945,
    year: '2024',
    awards: 'Cover Feature',
    location: 'Udaipur Haveli Terrace',
    story: 'Traditional textiles illuminated by evening dusk settling over Pichola waters.',
    exif: {
      camera: 'Sony A7R V',
      lens: '50mm f/1.2 GM',
      settings: '1/1000s · f/1.4 · ISO 100',
      focalLength: '50mm',
      aperture: 'f/1.4',
    },
    remote: 'https://images.unsplash.com/photo-1790773736710-87960a00c3e5?w=1200&auto=format&fit=crop&q=80',
  },
  {
    id: 'root-img-20221026-180655-1',
    title: 'Horizon in White',
    category: 'Golden Hour & Travel',
    w: 4000,
    h: 3000,
    year: '2024',
    awards: 'NatGeo Daily Dozen',
    location: 'White Rann of Kutch',
    story: 'Vast salt desert plains where the white horizon melts seamlessly into violet skies.',
    exif: {
      camera: 'Sony A7R V',
      lens: '24-70mm f/2.8 GM II',
      settings: '1/800s · f/5.6 · ISO 100',
      focalLength: '38mm',
      aperture: 'f/5.6',
    },
  },
  {
    id: 'unsplash-portrait-03',
    title: "The Artisan's Hands",
    category: 'Editorial',
    w: 600,
    h: 800,
    year: '2024',
    awards: 'Curator Pick',
    location: 'Weavers Quarter, Patan',
    story: 'Master weavers intertwining double-ikat silk threads with centuries of ancestral rhythm.',
    exif: {
      camera: 'Leica Q2',
      lens: '28mm f/1.7 Summilux',
      settings: '1/400s · f/2.0 · ISO 160',
      focalLength: '28mm',
      aperture: 'f/2.0',
    },
    remote: 'https://images.unsplash.com/photo-1790773779750-5537cbae9616?w=1200&auto=format&fit=crop&q=80',
  },
  {
    id: 'root-img-20220827-100214',
    title: 'Loom of Daylight',
    category: 'Editorial',
    w: 6000,
    h: 8000,
    year: '2024',
    awards: 'Print Collection',
    location: 'Calico Heritage Textile Atelier',
    story: 'Subtle textile textures bathed in gentle north-facing artisan window exposure.',
    exif: {
      camera: 'Sony A7R V',
      lens: '35mm f/1.4 GM',
      settings: '1/1000s · f/2.0 · ISO 100',
      focalLength: '35mm',
      aperture: 'f/2.0',
    },
  },
  {
    id: 'unsplash-portrait-05',
    title: 'Gaze of the Wanderer',
    category: 'Portraits',
    w: 600,
    h: 800,
    year: '2025',
    awards: 'Staff Pick',
    location: 'Pushkar Desert Dunes',
    story: 'Candid unposed glance captured as the sunset breeze swept warm amber sands.',
    exif: {
      camera: 'Sony A7R V',
      lens: '85mm f/1.4 GM',
      settings: '1/640s · f/1.8 · ISO 100',
      focalLength: '85mm',
      aperture: 'f/1.8',
    },
    remote: 'https://images.unsplash.com/photo-1790773640509-d139de8a4a07?w=1200&auto=format&fit=crop&q=80',
  },
  {
    id: 'root-img-20251029-105853',
    title: 'The Gold Velvet Hour',
    category: 'Golden Hour & Travel',
    w: 5160,
    h: 6880,
    year: '2025',
    awards: 'Award Winner',
    location: 'Little Rann Wildlife Sanctuary',
    story: 'Wild asses galloping across cracked earth at the golden juncture of dusk.',
    exif: {
      camera: 'Leica M11',
      lens: '50mm f/1.4 Noctilux',
      settings: '1/500s · f/1.4 · ISO 100',
      focalLength: '50mm',
      aperture: 'f/1.4',
    },
  },
  {
    id: 'unsplash-portrait-06',
    title: 'Twilight in Gujarat',
    category: 'Golden Hour & Travel',
    w: 600,
    h: 800,
    year: '2025',
    awards: 'Staff Pick',
    location: 'Modhera Sun Temple Steppes',
    story: '11th-century carved kund steps reflecting deep indigo sky and warm lamp flares.',
    exif: {
      camera: 'Fujifilm X-T5',
      lens: '56mm f/1.2 R WR',
      settings: '1/320s · f/1.8 · ISO 200',
      focalLength: '56mm',
      aperture: 'f/1.8',
    },
    remote: 'https://images.unsplash.com/photo-1790773540420-69b5aa27df20?w=1200&auto=format&fit=crop&q=80',
  },
  {
    id: 'root-img-20210717-195118',
    title: 'Quiet Solitude',
    category: 'Portraits',
    w: 3000,
    h: 4000,
    year: '2024',
    awards: 'Monochrome Honor',
    location: 'Sarkhej Roza Pavilions',
    story: 'Contemplative pose aligned with the serene Islamic stone lattices and water tanks.',
    exif: {
      camera: 'Sony A7R V',
      lens: '50mm f/1.2 GM',
      settings: '1/500s · f/1.4 · ISO 100',
      focalLength: '50mm',
      aperture: 'f/1.4',
    },
  },
  {
    id: 'root-img-20210114-182045',
    title: 'Dusk on Sabarmati',
    category: 'Golden Hour & Travel',
    w: 3000,
    h: 4000,
    year: '2024',
    awards: 'Staff Pick',
    location: 'Sabarmati Riverfront Promenade',
    story: 'The city lights awakening against calm ripples and drifting evening kites.',
    exif: {
      camera: 'Leica Q2',
      lens: '28mm f/1.7 Summilux',
      settings: '1/320s · f/2.8 · ISO 200',
      focalLength: '28mm',
      aperture: 'f/2.8',
    },
  },
  {
    id: 'root-img-20220903-215930',
    title: 'The Monsoon Gaze',
    category: 'Portraits',
    w: 2719,
    h: 4282,
    year: '2024',
    awards: 'Editor Selection',
    location: 'Lukshmi Vilas Grounds, Vadodara',
    story: 'Atmospheric mist and lush rain-soaked garden foliage creating a moody, evocative canvas.',
    exif: {
      camera: 'Sony A7R V',
      lens: '85mm f/1.4 GM',
      settings: '1/400s · f/1.8 · ISO 160',
      focalLength: '85mm',
      aperture: 'f/1.8',
    },
  },
]

export const categories = ['All', 'Portraits', 'Editorial', 'Architecture & Street', 'Golden Hour & Travel']

export const shootPackages = [
  {
    id: 'portrait',
    name: 'Fine-Art Portrait Session',
    duration: '2 Hours · 1 Location',
    price: '₹8,000',
    usdPrice: '$83',
    summary: 'Tailored for artists, founders, couples, or bespoke creative editorial portraits.',
    features: [
      '25 Master-graded high-resolution frames',
      'Location and styling consultation',
      'Full private digital archive for lifetime download',
      'Complimentary 35mm analog film roll scan',
      'Delivery within 5 business days',
    ],
    popular: false,
  },
  {
    id: 'editorial',
    name: 'Brand & Editorial Chronicle',
    duration: 'Half Day (4-5 Hours)',
    price: '₹16,000',
    usdPrice: '$167',
    summary: 'Ideal for fashion lookbooks, luxury hospitality, artisanal ateliers, and design studios.',
    features: [
      '60 Hand-retouched signature editorial frames',
      'Multi-outfit & dual-location flexibility',
      'Full worldwide commercial license',
      'Social media vertical crop suite & 4K video reel clips',
      '48-Hour expedited preview gallery',
    ],
    popular: true,
  },
  {
    id: 'wedding',
    name: 'Destination & Heirloom Story',
    duration: 'Full Day (8-10 Hours)',
    price: '₹35,000',
    usdPrice: '$365',
    summary: 'Cinematic, documentary-style wedding & intimate celebrations with genuine unposed warmth.',
    features: [
      '180+ Curated high-resolution story frames',
      'Bespoke Italian linen hardcover heirloom album (12x12")',
      'Second camera angle for comprehensive coverage',
      'High-speed teaser trailer reel within 24 hours',
      'Archival USB gift box with fine-art cotton prints',
    ],
    popular: false,
  },
]

export const addOns = [
  { id: 'film', name: 'Analog 35mm Film Roll (Kodak Portra 400)', price: '₹4,500' },
  { id: 'rush', name: '24-Hour Expedited Delivery', price: '₹6,000' },
  { id: 'drone', name: '4K Aerial Drone Perspective', price: '₹9,500' },
  { id: 'album', name: 'Custom Handbound Cotton Rag Photobook', price: '₹12,000' },
]

export const philosophyPillars = [
  {
    step: '01',
    title: 'The Natural Light Discipline',
    description: 'We do not rely on harsh strobes or synthetic umbrellas. We track the sun, harness gentle northern bounce, and let the natural luminescence of the scene wrap around the subject.',
    detail: 'Diffused morning rays, golden hour rakes, and twilight blue hours provide unmatched authenticity and depth.',
  },
  {
    step: '02',
    title: 'Unscripted Human Connection',
    description: 'The most timeless frames happen between the poses. We build rapport, create a relaxed atmosphere, and capture authentic laughter, quiet glances, and unguarded truth.',
    detail: 'No stiff smiles or awkward angles. Just genuine memories preserved in effortless beauty.',
  },
  {
    step: '03',
    title: 'Bespoke Color Alchemy',
    description: 'Every single deliverable photograph undergoes custom darkroom color development. We tune highlights, lift subtle shadows, and preserve organic skin tones inspired by analog film stocks.',
    detail: 'Calibrated on high-gamut reference displays for true-to-life prints and breathtaking digital screens.',
  },
]

export const gearKit = [
  { category: 'Bodies', item: 'Sony Alpha 7R V (61MP Full-Frame) & Fujifilm GFX 100S' },
  { category: 'Optics', item: 'Sony 35mm f/1.4 GM, 50mm f/1.2 GM, 85mm f/1.4 GM' },
  { category: 'Specialty Glass', item: 'Leica Summilux 28mm f/1.7 & Vintage Helios 44-2 58mm' },
  { category: 'Filters & Shapers', item: 'Moment CineBloom 10% Diffusion & B+W Circular Polarizers' },
]

export const accolades = [
  { name: 'Vogue India', label: 'Wedding Portfolio Spotlight 2024' },
  { name: 'NatGeo YourShot', label: 'Daily Dozen International Selection' },
  { name: 'Condé Nast Traveller', label: 'Heritage Gujarat Feature' },
  { name: 'Fearless Photographers', label: 'Collection 64 Award Winner' },
]

export const testimonials = [
  {
    quote: 'Ayush has this rare gift of making you forget a camera even exists. The portraits he captured feel like stills from an art film. Truly one of the finest artists in Gujarat.',
    name: 'Ananya & Siddharth',
    role: 'Destination Wedding, Udaipur',
    photo: 'unsplash-portrait-01',
  },
  {
    quote: 'Our brand campaign needed to feel organic, tactile, and grounded in Gujarati craftsmanship. Ayush delivered beyond our highest expectations. The color science is unmatched.',
    name: 'Devanshi Mehta',
    role: 'Creative Director, Vana Ateliers',
    photo: 'unsplash-portrait-03',
  },
  {
    quote: 'Working with Ayush was effortless. The photographs capture the quiet architectural dignity of the stepwell with incredible dynamic range. A master of natural light.',
    name: 'Vikramaditya Rao',
    role: 'Architect & Heritage Conservator',
    photo: 'root-img-20220824-185013',
  },
]

export const sizes = [480, 960, 1600]
